#!/usr/bin/env node
/** Concatenates prisma/schema.base.prisma + prisma/fragments/*.prisma (not _local-base) into prisma/schema.prisma.
 *  Fails if a fragment declares datasource/generator. Usage: node scripts/assemble-prisma.mjs [--check] */
import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const base = path.join(root, 'prisma/schema.base.prisma');
const fragDir = path.join(root, 'prisma/fragments');
if (!fs.existsSync(base)) { console.error('FAIL: prisma/schema.base.prisma missing'); process.exit(1); }
const frags = fs.existsSync(fragDir) ? fs.readdirSync(fragDir).filter((f) => f.endsWith('.prisma') && !f.startsWith('_')).sort() : [];
let out = '// GENERATED by scripts/assemble-prisma.mjs - do not edit\n' + fs.readFileSync(base, 'utf8') + '\n';
let bad = false;
for (const f of frags) {
  const s = fs.readFileSync(path.join(fragDir, f), 'utf8');
  if (/^\s*(datasource|generator)\s/m.test(s)) { console.error(`FAIL: ${f} contains datasource/generator`); bad = true; }
  if (/^\s*model\s+(Organization|User)\s*\{/m.test(s)) { console.error(`FAIL: ${f} redefines Organization/User (belongs in base)`); bad = true; }
  out += `\n// ---- fragment: ${f}\n${s}\n`;
}
if (bad) process.exit(1);
if (!process.argv.includes('--check')) fs.writeFileSync(path.join(root, 'prisma/schema.prisma'), out);
console.log(`OK: base + ${frags.length} fragment(s): ${frags.join(', ') || '(none)'}`);
